---
title: "Membros"

site: distill::distill_website
---




[Vitor de Moraes Peixoto](http://lattes.cnpq.br/4676437210734787)  <br/> \hfill\break
**Coordenador** <br/> \hfill\break
Professor Associado <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Centro de Ciências do Homem <br/> \hfill\break
Laboratório de Estudos da Sociedade Civil e do Estado <br/> \hfill\break
E-mail: moraespeixoto@gmail.com <br/> \hfill\break

[Ralph André Crespo](http://lattes.cnpq.br/7250750885312461) <br/> \hfill\break
Doutorando do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: pr.ralph@yahoo.com.br <br/> \hfill\break

[Jheniffer Vieira de Almeida](http://lattes.cnpq.br/1477388811747167) <br/> \hfill\break
Doutoranda do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: jheniffer.vi@gmail.com <br/> \hfill\break

[Raphael de Mello Veloso](http://lattes.cnpq.br/9433034841064768) <br/> \hfill\break
Doutorando do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: raphamv@gmail.com  <br/> \hfill\break

[Gisele Braga Bastos](http://lattes.cnpq.br/1675744772217864) <br/> \hfill\break
Doutoranda do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/>\hfill\break
E-mail: gibragabastos@gmail.com <br/> \hfill\break

[Jessica Matheus de Souza](http://lattes.cnpq.br/6717255818088404) <br/> \hfill\break
Doutoranda do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: jessicamatheus@outlook.com  <br/> \hfill\break

[Wallace da Silva Mello](http://lattes.cnpq.br/8178088513307546) <br/> \hfill\break
Doutorando do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: wallace_sm89@hotmail.com <br/> \hfill\break

[Thiago Pimentel Soares](http://lattes.cnpq.br/5038496684551538) <br/> \hfill\break
Mestrando do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: tpsoares@hotmail.com <br/> \hfill\break

[Rafael Soares Salles](http://lattes.cnpq.br/6781198318316057) <br/> \hfill\break
Mestrando do Programa de Pós-Graduação em Sociologia Politica <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break 
E-mail: rafael.salles@outlook.com <br/> \hfill\break

[Larissa Martins Marques](http://lattes.cnpq.br/8424422005329610) <br/> \hfill\break
Graduanda do Curso de Administração Pública <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro  <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: larissamarques@pq.uenf.br <br/> \hfill\break

[Matheus Virginio Harduim Machado](http://lattes.cnpq.br/6781198318316057) <br/> \hfill\break
Graduando do Curso de Ciências Sociais <br/> \hfill\break
niversidade Estadual do Norte Fluminense Darcy Ribeiro  <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: mattharduim@gmail.com <br/> \hfill\break

[Fernanda da Silva Souza](http://lattes.cnpq.br/7181203038300743) <br/> \hfill\break
Graduanda do Curso de Ciências Sociais <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: fer.souzaa1@outlook.com <br/> \hfill\break

[Lara Bernardo de Oliveira](http://lattes.cnpq.br/6943283489647623) <br/> \hfill\break
Graduanda do Curso de Ciências Sociais <br/> \hfill\break 
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: lalabernardo1904@gmail.com <br/> \hfill\break

[Paula Regis]() <br/> \hfill\break
Graduanda do Curso de Administração Pública <br/> \hfill\break
Universidade Estadual do Norte Fluminense Darcy Ribeiro <br/> \hfill\break
Laboratório de Estudos do Estado e da Sociedade Civil <br/> \hfill\break
E-mail: regispaularegis@gmail.com <br/>\hfill\break

<br/><br/> \hfill\break \hfill\break
Falta inserir os pós doutorandos.
<br/><br/> \hfill\break \hfill\break
